Repository googleapis/python-iam, pull requests merged in 2020-06, with the labels that each got.

#20 docs: fix a tiny typo in the README
  README.rst
Labels: automerge, cla: yes

#21 fix: update default retry config
  .flake8
  .gitignore
  .kokoro/publish-docs.sh
  .kokoro/release.sh
  .kokoro/samples/lint/common.cfg
  .kokoro/samples/lint/continuous.cfg
  .kokoro/samples/lint/periodic.cfg
  .kokoro/samples/lint/presubmit.cfg
  .kokoro/samples/python3.6/common.cfg
  .kokoro/samples/python3.6/continuous.cfg
  .kokoro/samples/python3.6/periodic.cfg
  .kokoro/samples/python3.6/presubmit.cfg
  .kokoro/samples/python3.7/common.cfg
  .kokoro/samples/python3.7/continuous.cfg
  .kokoro/samples/python3.7/periodic.cfg
  .kokoro/samples/python3.7/presubmit.cfg
  .kokoro/samples/python3.8/common.cfg
  .kokoro/samples/python3.8/continuous.cfg
  .kokoro/samples/python3.8/periodic.cfg
  .kokoro/samples/python3.8/presubmit.cfg
  .kokoro/test-samples.sh
  MANIFEST.in
  docs/conf.py
  docs/index.rst
  docs/multiprocessing.rst
  google/cloud/iam_credentials.py
  google/cloud/iam_credentials_v1/__init__.py
  google/cloud/iam_credentials_v1/gapic/iam_credentials_client.py
  google/cloud/iam_credentials_v1/gapic/iam_credentials_client_config.py
  google/cloud/iam_credentials_v1/gapic/transports/iam_credentials_grpc_transport.py
  google/cloud/iam_credentials_v1/proto/common_pb2.py
  google/cloud/iam_credentials_v1/proto/iamcredentials_pb2.py
  google/cloud/iam_credentials_v1/proto/iamcredentials_pb2_grpc.py
  google/cloud/iam_credentials_v1/types.py
  noxfile.py
  scripts/decrypt-secrets.sh
  scripts/readme-gen/readme_gen.py
  scripts/readme-gen/templates/README.tmpl.rst
  scripts/readme-gen/templates/auth.tmpl.rst
  scripts/readme-gen/templates/auth_api_key.tmpl.rst
  scripts/readme-gen/templates/install_deps.tmpl.rst
  scripts/readme-gen/templates/install_portaudio.tmpl.rst
  synth.metadata
  synth.py
  testing/.gitignore
Labels: automerge, cla: yes, context: full

#23 chore: update grpc version
  google/cloud/iam_credentials_v1/proto/common_pb2.py
  google/cloud/iam_credentials_v1/proto/common_pb2_grpc.py
  google/cloud/iam_credentials_v1/proto/iamcredentials_pb2.py
  google/cloud/iam_credentials_v1/proto/iamcredentials_pb2_grpc.py
  synth.metadata
Labels: cla: yes, context: full

#24 chore: update Py2 support msg to reflect passage of time
  docs/_templates/layout.html
  synth.metadata
Labels: cla: yes, context: full
