Repository googleapis/python-iam, pull requests merged in 2021-01, with the labels that each got.

#48 feat: add from_service_account_info factory and fix sphinx identifiers
  docs/credentials_v1/iam_credentials.rst
  docs/credentials_v1/services.rst
  docs/credentials_v1/types.rst
  google/cloud/iam_credentials_v1/services/iam_credentials/async_client.py
  google/cloud/iam_credentials_v1/services/iam_credentials/client.py
  google/cloud/iam_credentials_v1/types/common.py
  synth.metadata
  tests/unit/gapic/credentials_v1/test_iam_credentials.py
Labels: api: iam, cla: yes, context: full

#50 chore: move libcst requirement to extras
  UPGRADING.md
  docs/UPGRADING.md
  scripts/fixup_credentials_v1_keywords.py
  setup.py
Labels: api: iam, automerge, cla: yes

#54 build: migrate to flakybot
  .kokoro/test-samples.sh
  .kokoro/trampoline_v2.sh
Labels: api: iam, cla: yes
